# Introduction to Machine Learning
This tutorial is based on the official tutorial titled [Working With Data](http://scikit-learn.org/stable/tutorial/text_analytics/working_with_text_data.html) by the `scikit-learn` team and a similarly-minded [tutorial](https://github.com/jonhare/WAIS-ML101) conducted by Dr Jonathon Hare in 2016. Compared to those versions, the current tutorial features a dataset that has been published by [Kaggle](https://www.kaggle.com) as part of a competition that they organised for [Detecting Insults in Social Commentary](https://www.kaggle.com/c/detecting-insults-in-social-commentary). Furthermore, a number of changes have been carried in the code of the above-mentioned tutorials in order to include `pandas` in the data pre-processing stage, and to assure compatibility with the updated version of `scikit-learn`.

In this tutorial you will learn how to:
* Extract feature vectors from text documents
* Load, inspect and pre-process a dataset of comments on social media
* Train a classifier to predict whether a comment on social media is insulting or not
* Use Grid Search in order to tune better the hyper-parameters of your Machine Learning pipeline

In order to run this iPython Notebook (Python 2), [Jupyter](http://jupyter.org/) should be installed in your machine. Besides Jupyter, the following Python packages should also be installed: (i) `pandas` and (ii) `scikit-learn`. The easiest way to install all of these together is with [Anaconda](https://www.anaconda.com/) (Windows, macOS and Linux installers available).

# Loading the Kaggle Dataset
For the purposes of this tutorial, we will be using a dataset of comments on social media along with their classification labels (i.e. "insult" or "neutral"). The dataset is encoded in binary-encoded `pickle` files which reside in `./Kaggle/train.p`.

In [38]:
kaggle_dataset_location = '../Kaggle/train.p' # The location of the Kaggle dataset

In [39]:
import cPickle as pickle

# Loading the binary-encoded pickle files from the designated location.
with open(kaggle_dataset_location, 'rb') as f:
    kaggle_dataset = pickle.load(f)

The `kaggle_dataset` variable contains the dataset as a pythonic dictionary of lists. We will be using the `pandas` library in order to tranform this structure into a `pandas.DataFrame` which will simplify the data inspection and pre-processing process.

In [40]:
import pandas as pd

kaggle_dataset_df = pd.DataFrame(kaggle_dataset)
print len(kaggle_dataset_df) # Number of rows in the loaded DataFrame

3947


We print the first 10 rows of the `DataFrame` in order to get an understanding of the structure of the dataset.

In [41]:
print kaggle_dataset_df.head(n=10)

     Class                                            Comment             Date
0   insult                                 You fuck your dad.  20120618192155Z
1  neutral  i really don't understand your point.\xa0 It s...  20120528192215Z
2  neutral  A\\xc2\\xa0majority of Canadians can and has b...              NaN
3  neutral  listen if you dont wanna get married to a man ...              NaN
4  neutral  C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1eddn...  20120619094753Z
5  neutral  @SDL OK, but I would hope they'd sign him to a...  20120620171226Z
6  neutral                        Yeah and where are you now?  20120503012628Z
7   insult  shut the fuck up. you and the rest of your fag...              NaN
8   insult  Either you are fake or extremely stupid...mayb...  20120502173553Z
9   insult  That you are an idiot who understands neither ...  20120620160512Z


In [46]:
sum(kaggle_dataset_df['Class'] == 'neutral')

2898

In [47]:
print kaggle_dataset_df['Comment'][1]
print kaggle_dataset_df['Comment'][10]

i really don't understand your point.\xa0 It seems that you are mixing apples and oranges.
@jdstorm dont wish him injury but it happened on its OWN and i DOUBT he's injured, he looked embarrassed to me


In [48]:
# Print all the available columns of the dataset.
print(kaggle_dataset_df.columns)
# Define the target column which we want to predict.
target_column = u'Class'

Index([u'Class', u'Comment', u'Date'], dtype='object')


In [49]:
# Returns the category codes of each of the classes in the target-column.
inputs = kaggle_dataset_df['Comment']
outputs = kaggle_dataset_df['Class'].astype('category').cat.codes

In [52]:
class_names = kaggle_dataset_df['Class'].astype('category').cat.categories.tolist()
print class_names

[u'insult', u'neutral']


In order to test the performance of our algorithm, it is very important to to test its performance on data that it hasn't *seen* during training. Luckily, `sklearn` includes an appropriate function that splits the items for a dataset into random train and test subsets.

We set the portion of the original dataset that will be used for testing.

In [51]:
from sklearn.model_selection import train_test_split

test_size = 0.2
# Set a random_state number for replicability of the experiments.
random_state = 10
# Split dataset into training and testing according to the test_size variable.
# output_train and output_test are lists containing the classes' indices.
input_train, input_test = train_test_split(inputs.tolist(), test_size=test_size, random_state=random_state)
y_train, y_test = train_test_split(outputs.tolist(), test_size=test_size, random_state=random_state)

# Extracting Features from Text: The Bag-of-Words Approach
In order to be able to use text documents$^1$ as either input to Machine Learning algorithms, we need to follow a process that would turn them into numerical feature vectors. We generally refer to this process as *vectorisation*. The most intuitive way to do so is the **bags-of-words** approach, which is carried out as follows:
1. Identify all the words that occur in the documents of a training set.
2. Assign a fixed integer ID to each one of those words. For example in Python you could build a dictionary that would map each word to each corresponding integer ID:
 ```python
 dictionary = {'I': 1,
               'study': 2,
               'machine': 3,
               'learning': 4,
               ...}
 ```
3. For each document in the training set, we count the number of occurrences of each word, and we store it in $X[d, w]$, as the value of the $w$-th feature for the $d$-th document, where $w$ is the index of the word in the dictionary.

The bags-of-words representation implies that total number of features is the number of distinct words in the corpus, which typically is larger than 100k. 

While storing all these values in a `numpy` array would require substantial amount of memory, most values in $X$ will be zeros since for a given document only a small subset of the set of the distinct words in the dataset will be present. For this reason, we say that bags-of-words are typically high-dimensional sparse datasets. We can save a lot of memory by only storing the non-zero parts of the feature vectors in memory. `scipy.sparse` matrices are data structures that do exactly this, and scikit-learn has built-in support for these structures.

In `scipy` text preprocessing, tokenising and stop-words (e.g. "and", "or" and "that") filtering are included in a high-level component that is able to build a dictionary of features and transform documents to feature vectors:

$^1$ Text documents can vary substantially in length and writing style. In our case, we refer to text documents as the short-lengthed comments of our Kaggle dataset, but the techniques presented in this tutorial could work on much longer collections, such as articles or books.

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import TweetTokenizer
word_tokenizer = TweetTokenizer(preserve_case=False, 
                                strip_handles=True, 
                                reduce_len=True).tokenize

count_vectorizer = CountVectorizer(ngram_range=(1, 1),
                                   stop_words=None,
                                   tokenizer=word_tokenizer,
                                   # Ignore terms that have a document frequency strictly higher than the given threshold.
                                   # If float, the parameter represents a proportion of documents, integer absolute counts.
                                   max_df=1.0,
                                   # Ignore terms that have a document frequency strictly lower than the given threshold.
                                   # If float, the parameter represents a proportion of documents, integer absolute counts.
                                   min_df=1)
count_vectorizer

CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=<bound method TweetTokenizer.tokenize of <nltk.tokenize.casual.TweetTokenizer instance at 0x7f5e7a9bc0e0>>,
        vocabulary=None)

## Working on a Toy Example
Let’s use it to tokenize and count the word occurrences of a minimalistic corpus of text documents:

In [11]:
toy_corpus = [u'You have studied Machine Learning',
              u'I love Machine Learning',
              u'Looking forward to #WAISAwayDay',
              u'Have you studied Machine Learning']

# Fits and tranforms the corpus in its bag-of-words representation.
toy_count = count_vectorizer.fit_transform(toy_corpus) 

During the fitting process each team is assigned a unique integer index corresponding to a column in the resulting `toy_count` matrix (i.e. equivalent to the $X$ matrix that has been mentioned in the description of this section of the tutorial).

In [54]:
print toy_count # This is the memory-efficient representation of a sparse matrix.
print toy_count.toarray()

  (0, 4)	1
  (0, 7)	1
  (0, 8)	1
  (0, 2)	1
  (0, 10)	1
  (1, 6)	1
  (1, 3)	1
  (1, 4)	1
  (1, 7)	1
  (2, 0)	1
  (2, 9)	1
  (2, 1)	1
  (2, 5)	1
  (3, 4)	1
  (3, 7)	1
  (3, 8)	1
  (3, 2)	1
  (3, 10)	1
[[0 0 1 0 1 0 0 1 1 0 1]
 [0 0 0 1 1 0 1 1 0 0 0]
 [1 1 0 0 0 1 0 0 0 1 0]
 [0 0 1 0 1 0 0 1 1 0 1]]


You can see that the first and the last rows of the array are identical. This is happening because they correspond to comments with the same words, and, thus, are encoded in equal vectors, which leads to loss of valuable information. `CountVectorizer` also supports counts of n-grams of words or consecutive characters. N-grams are runs of consecutive characters or words, so for example in the case of word bi-grams, every consecutive pair of words would be a feature. Support for n-grams can be enabled by adjusting the `ngram_range` variable during the initialisation of the `CountVectorizer`.

In the initialisation of `CountVectorizer` set the `ngram_range` variable to `(1, 2)`, and check the resulting `toy_count` matrix by running `toy_count.toarray()`. Do the results make sense?

The interpretation of the columns can be retrieved as follows:

In [13]:
count_vectorizer.get_feature_names()

[u'#waisawayday',
 u'forward',
 u'have',
 u'i',
 u'learning',
 u'looking',
 u'love',
 u'machine',
 u'studied',
 u'to',
 u'you']

Once the vectoriser is fitted, you can retrieve the index of a particular word in the dictionary by simply calling:

In [14]:
count_vectorizer.vocabulary_.get(u'machine')

7

For further details about the functionality of `CountVectorizer` please refer [here](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html#sklearn.feature_extraction.text.CountVectorizer).

## Working on the Kaggle Dataset

In [55]:
# Print a small part of the comments that will be used for training.
input_train[:5] 

[u"Only if Ronald McDonald gives him time off from his regular job as a McSlave at McDoonald's.",
 u"You're a fucking joke.",
 u'Magic Number, Magic Underpants = No Big Deal',
 u"YOU HAVE A BEAUTIFUL BODY. What's wrong with a man looking at a woman with a beautiful body ESPECIALLY NICE HIPS? If I'm stalker for that then every dude I know is a stalker as well.",
 u'So, now we know what you are by your own identification, fool, will you kindly moveon.org and stop cluttering up the place and so we intelligent posters can post?']

In [56]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import TweetTokenizer
word_tokenizer = TweetTokenizer(preserve_case=False, 
                                strip_handles=True, 
                                reduce_len=True).tokenize

count_vectorizer = CountVectorizer(ngram_range=(1, 1),
                                   stop_words=None,
                                   tokenizer=word_tokenizer,
                                   # Ignore terms that have a document frequency strictly higher than the given threshold.
                                   # If float, the parameter represents a proportion of documents, integer absolute counts.
                                   max_df=1.0,
                                   # Ignore terms that have a document frequency strictly lower than the given threshold.
                                   # If float, the parameter represents a proportion of documents, integer absolute counts.
                                   min_df=1)
count_vectorizer

CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=<bound method TweetTokenizer.tokenize of <nltk.tokenize.casual.TweetTokenizer instance at 0x7f5eb8953cb0>>,
        vocabulary=None)

In [57]:
# Fits and tranforms the corpus in its bag-of-words representation.
X_train_count = count_vectorizer.fit_transform(input_train)

During the fitting process each team is assigned a unique integer index corresponding to a column in the resulting `X_train_count` matrix (i.e. equivalent to the $X$ matrix that has been mentioned in the description of this section of the tutorial).

In [58]:
print X_train_count.shape
print X_train_count.toarray()

(3157, 14730)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 4 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 [0 4 0 ... 0 0 0]]


### From Occurrences To Frequencies
Occurrence count is a good start. However, longer documents will have higher average count values than shorter documents, even though they might talk about similar topics. To avoid these potential discrepancies, it suffices to divide the number of occurrences of each word in a document by the total number of words in the document. The number of times a term occurs in a document, divided by the number of terms in a document is called the **term frequency** (**tf**).

Another refinement on top of term frequency is to downscale weights for words that occur in many documents in the corpus, and are therefore less informative than those that occur only in a smaller portion of the corpus. In order to achieve this we can weight terms on the basis of the **inverse document frequency** (**idf**). The *document frequency* is the number of documents a given word occurs in; the inverse document frequency is often defined as the total number of documents in the corpurs divided by the document frequency.

Combining tf and idf results in a *family of weightings* (tf is usually multiplied by idf, but there a few different variations of how idf is computed) known as **term frequency-inverse document frequency** (**tf–idf**).

Both tf and tf–idf on our `toy_corpus` can be computed using `scikit-learn` as follows:

In [15]:
# import numpy as np
# idf = (np.log(4.0 / 2) + 1) * 0.2

0.3386294361119891

In [59]:
from sklearn.feature_extraction.text import TfidfTransformer

# Computing tf using the counts that have been computed from the CountVectorizer.
tf_transformer = TfidfTransformer(use_idf=False, norm='l1')
X_train_tf = tf_transformer.fit_transform(toy_count)

print X_train_tf.shape
print X_train_tf.toarray()

(4, 11)
[[0.   0.   0.2  0.   0.2  0.   0.   0.2  0.2  0.   0.2 ]
 [0.   0.   0.   0.25 0.25 0.   0.25 0.25 0.   0.   0.  ]
 [0.25 0.25 0.   0.   0.   0.25 0.   0.   0.   0.25 0.  ]
 [0.   0.   0.2  0.   0.2  0.   0.   0.2  0.2  0.   0.2 ]]


In [60]:
toy_count.toarray()[2]

array([1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0])

In [61]:
# Computing tf-idf using the counts that have been computed from the CountVectorizer.
tfidf_transformer = TfidfTransformer(use_idf=True, norm='l1', smooth_idf=False)
X_train_tfidf = tfidf_transformer.fit_transform(toy_count)

print X_train_tfidf.shape
print X_train_tfidf.toarray()

(4, 11)
[[0.         0.         0.22118748 0.         0.16821878 0.
  0.         0.16821878 0.22118748 0.         0.22118748]
 [0.         0.         0.         0.32475635 0.17524365 0.
  0.32475635 0.17524365 0.         0.         0.        ]
 [0.25       0.25       0.         0.         0.         0.25
  0.         0.         0.         0.25       0.        ]
 [0.         0.         0.22118748 0.         0.16821878 0.
  0.         0.16821878 0.22118748 0.         0.22118748]]


Rather than transforming the raw counts with the `TfidfTransformer`, it is alternatively possible to use the `TfidfVectorizer` to directly parse the dataset. We compute tf-idf scores on the Kaggle dataset as follows:

In [122]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect = TfidfVectorizer(ngram_range=(1, 2),
                             stop_words='english',
                             # tokenizer='word_tokenizer',
                             # Ignore terms that have a document frequency strictly higher than the given threshold.
                             # If float, the parameter represents a proportion of documents, integer absolute counts.
                             max_df=0.75,
                             # Ignore terms that have a document frequency strictly lower than the given threshold.
                             # If float, the parameter represents a proportion of documents, integer absolute counts.
                             min_df=5,
                             # tf-idf parameters
                             use_idf=True, norm='l1', smooth_idf=False)

X_train_tfidf = tfidf_vect.fit_transform(input_train)

print X_train_tfidf.shape
print X_train_tfidf.toarray()

(3157, 1989)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


Try filtering out terms that are either too frequent or infrequent in the dataset by adjusting the `max_df` and `min_df` variable respectively. This is an easy way of not only filtering out the less informative words but also reducing the number of features (less storage complexity).

# Building a Predictive Model using K-Nearest-Neighbours
Now that we have our training features and the labels of each post, we can train a classifier to predict whether a message is insulting or not. Let's start with a KNN classifier, which provides a simple baseline, although is perhaps not the best classifier for this task:

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors=3).fit(X_train_tfidf, y_train)

To try to predict the outcome on a new comment we need to extract the features using almost the same feature extracting chain as before. The differences are that we call (i) `transform` instead of `fit_transform` on the transformer or vectoriser, and (ii) `predict` on the classifier since they have both been fit to the training set.

You can test your own comments by changing the text in the `test_comment` variable. Does your classifier identify all the insults properly?

In [66]:
test_comment = 'Fuck you!!'
test_comment_tfidf = tfidf_vect.transform([test_comment])
y_pred = knn_clf.predict(test_comment_tfidf)

print'%s: %s' % (test_comment, class_names[y_pred[0]])

Fuck you!!: insult


## Evaluating the Performance on the Test Set
We will be evaluating the performance of our KNN classifier on the *unseen* data of the test set based on the accuracy metric. In a binary classification task, such as ours, the accuracy with which a model predicts a specific class $c$ (e.g. insults) is formally defined as:

\begin{align}
\frac{\sum \text{TP} + \sum \text{TN}}{\sum \text{TP} + \sum \text{FP} + \sum \text{TN} + \sum \text{FN}}
\end{align}
where:
* $\text{TP}$ refers to True Positive predictions: both the predicted and the empirical labels are $c$
* $\text{TN}$ refers to True Negative predictions: both the predicted and the empirical labels are $\neq c$
* $\text{FP}$ refers to False Positive predictions: the predicted label is $c$ but the empirical label $\neq c$
* $\text{FN}$ refers to False Negative predictions: the predicted label is $\neq c$ but the empirical label is $c$

In [67]:
from sklearn import metrics

X_test_tfidf = tfidf_vect.transform(input_test)
y_pred = knn_clf.predict(X_test_tfidf)
print 'Accuracy: %.2f' % (metrics.accuracy_score(y_test, y_pred))


Accuracy: 0.75


### Building a Pipeline
In order to make our pipeline (i.e. vectoriser or transformer $\rightarrow$ classifier) easier to work with, `scikit-learn` provides the `Pipeline` class that behaves like a compound classifier.

In [74]:
from sklearn.pipeline import Pipeline
clf_pipeline = Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1, 1),
                                               stop_words='english',
                                               tokenizer=word_tokenizer,
                                               # If float, the parameter represents a proportion of documents, integer absolute counts.
                                               max_df=1.0,
                                               # Ignore terms that have a document frequency strictly lower than the given threshold.
                                               # If float, the parameter represents a proportion of documents, integer absolute counts.
                                               min_df=1,
                                               # tf-idf parameters
                                               use_idf=True, norm='l1', smooth_idf=False)),
                         ('clf', KNeighborsClassifier(n_neighbors=3))])

The names `tfidf` and `clf` (classifier) are arbitrary. We shall see their use in the section on grid search, below. We can now train (on the training set) and test (on the test set) the model in a similar fashion to when we had all the different components separate.

In [75]:
# Model Training
clf_pipeline.fit(input_train, y_train)
y_pred = clf_pipeline.predict(input_test) # We are making prediction on the test set.
print 'Accuracy: %.2f' % (metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.76


Let's see if we can do better with a linear Support Vector Machine (SVM). We can change the learner by just plugging a different classifier object into our pipeline as follows:

In [76]:
from sklearn.linear_model import SGDClassifier
clf_pipeline = Pipeline([('tfidf', TfidfVectorizer(ngram_range=(1, 1),
                                               stop_words='english',
                                               tokenizer=word_tokenizer,
                                               # If float, the parameter represents a proportion of documents, integer absolute counts.
                                               max_df=0.75,
                                               # Ignore terms that have a document frequency strictly lower than the given threshold.
                                               # If float, the parameter represents a proportion of documents, integer absolute counts.
                                               min_df=3,
                                               # tf-idf parameters
                                               use_idf=True, norm='l2', smooth_idf=False)),
                         ('clf', SGDClassifier(loss='hinge',
                                           penalty='l2',
                                           tol=1e-5,
                                           random_state=random_state))])
# Model Training
clf_pipeline.fit(input_train, y_train)

Pipeline(memory=None,
     steps=[('tfidf', TfidfVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=0.75, max_features=None, min_df=3,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=Fal...y='l2', power_t=0.5, random_state=10, shuffle=True,
       tol=1e-05, verbose=0, warm_start=False))])

In [77]:
y_pred = clf_pipeline.predict(input_test) # We are making prediction on the test set.
print 'Accuracy: %.2f' % (metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.84


`scikit-learn` further provides utilities for a more detailed performance analysis of the results using different metrics (i.e. precision, recall, and f1-score). Support refers to the number of samples that belong to each particular class.

For further details about those you can have a look [here](https://en.wikipedia.org/wiki/Precision_and_recall).

In [78]:
print(metrics.classification_report(y_test, 
                                    y_pred,
                                    target_names=class_names))

             precision    recall  f1-score   support

     insult       0.66      0.64      0.65       186
    neutral       0.89      0.90      0.89       604

avg / total       0.84      0.84      0.84       790



Like we did before, we can test how well our classifier is doing by inputing our own comments.

In [79]:
test_comment = 'Fuck you!'
y_pred = clf_pipeline.predict([test_comment])

print'%s: %s' % (test_comment, class_names[y_pred[0]])

Fuck you!: insult


# Parameter Tuning using Grid Search
We have already encountered some parameters such as `use_idf` in the `TfidfTransformer` (and `TfidfVectorizer`). Classifiers tend to have many parameters as well. For example `KNeighborsClassifier` includes parameter for the number of neighbours and `SGDClassifier` has a penalty parameter alpha and configurable loss and penalty terms in the objective function.

Instead of tweaking the parameters of the various components of the chain, it is possible to run an exhaustive search of the best parameters on a grid of possible values. Let's use this to explore whether we can make the KNeighborsClassifier perform as well as our linear SVM.

In [80]:
knn_pipeline = Pipeline([('tfidf', TfidfVectorizer()),
                         ('clf', KNeighborsClassifier(n_neighbors=3))])

from sklearn.model_selection import GridSearchCV
parameters = {'tfidf__ngram_range': [(1, 1), (1, 2), (1, 3), (1, 4)],
              'tfidf__use_idf': (True, False),
              'clf__n_neighbors': (1, 3, 5, 7, 9)}

Obviously, such an exhaustive search can be expensive. If we have multiple CPU cores at our disposal, we can tell the grid searcher to try these eleven parameter combinations in parallel with the `n_jobs` parameter. If we give this parameter a value of -1, grid search will detect how many cores are installed and uses them all.

In [33]:
knn_pipeline = GridSearchCV(knn_pipeline, param_grid=parameters, n_jobs=-1)

The grid search instance behaves like a normal `scikit-learn` model.

In [34]:
knn_pipeline.fit(input_train, y_train)

GridSearchCV(cv=None, error_score='raise',
       estimator=Pipeline(memory=None,
     steps=[('tfidf', TfidfVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm=u'l2', preprocessor=None, smooth_idf=Tru...owski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform'))]),
       fit_params=None, iid=True, n_jobs=-1,
       param_grid={'tfidf__use_idf': (True, False), 'tfidf__ngram_range': [(1, 1), (1, 2), (1, 3), (1, 4)], 'clf__n_neighbors': (1, 3, 5, 7, 9)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

We can get the optimal parameters out by inspecting the object's `grid_scores_` attribute, which is a list of parameters/score pairs. To get the best scoring attributes, we do as follows:

In [133]:
best_parameters, score, _ = max(knn_pipeline.grid_scores_, key=lambda x: x[1])
for param_name in sorted(parameters.keys()):
    print("%s: %r" % (param_name, best_parameters[param_name]))
print score

clf__n_neighbors: 9
tfidf__ngram_range: (1, 1)
tfidf__use_idf: True
0.805194805195


Let's test and see how well new comments are classified on our `knn_pipeline`.

In [37]:
test_comment = 'I do not agree!'
y_pred = knn_pipeline.predict([test_comment])

print'%s: %s' % (test_comment, class_names[y_pred[0]])

I do not agree!: neutral


# Exploring K-Means Clustering
Now that we have extracted features from our training documents we're in a position to experiment with clustering. We will use K-Means as its one of the most intuitive clustering methods, although it does have a few limitations.

K-Means clustering with 5 clusters can be achieved as follows:

In [163]:
from sklearn.cluster import KMeans
num_clusters = 500
k_means = KMeans(num_clusters)
k_means.fit(X_train_tfidf)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=500, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

The assignments of the original posts to cluster id is given by `km.labels_` once `km.fit(...)` has been called. The centroids of the clusters is given by `km.cluster_centers_`. Intuitively, the vector that describes the centre of a cluster is just like any other feature vector. An interesting way to explore what each cluster is representing is to calculate and print the top weighted (either by occurrence or tf-idf) terms for that cluster:

In [171]:
order_centroids = k_means.cluster_centers_.argsort()[:, ::-1]
terms = tfidf_vect.get_feature_names()
for i in range(num_clusters):
    print "Cluster %d:" % i,
    for ind in order_centroids[i, :5]:
        print ' %s' % terms[ind],
        print

Cluster 0:  bitches
 money
 ball
 yo
 nigga
Cluster 1:  posted
 control
 hope
 sure
 comment
Cluster 2:  ho
 da
 xa0
 2011
 fox news
Cluster 3:  fuck
 zero
 fucked
 forum
 forward
Cluster 4:  night
 tells
 laugh
 live
 sleep
Cluster 5:  don
 zero
 fucker
 forward
 fox
Cluster 6:  washington
 zero
 fucker
 forward
 fox
Cluster 7:  lock
 hey
 idiot
 zero
 forum
Cluster 8:  goes
 zero
 fuck just
 forum
 forward
Cluster 9:  xc2
 xc2 xa0
 xa0
 blow
 gay
Cluster 10:  came
 idiot
 zero
 fucker
 fox
Cluster 11:  don
 like
 zero
 friend
 fuck just
Cluster 12:  fool
 really
 fucker
 fox
 fox news
Cluster 13:  moron
 zero
 fuckin
 fox
 fox news
Cluster 14:  complete
 idiot
 sir
 waste
 president
Cluster 15:  holy shit
 holy
 shit
 didn
 science
Cluster 16:  idiot
 father
 death
 need
 fucking
Cluster 17:  xa0
 zero
 fucker
 forward
 fox
Cluster 18:  wearing
 head
 forgot
 forum
 forward
Cluster 19:  talking
 fucked
 forum
 forward
 fox
Cluster 20:  sarcasm
 forgot
 forum
 forward
 fox
Cluster 21:

 di
 ban
 la
Cluster 250:  eat
 just
 zero
 form
 forward
Cluster 251:  nget
 fuck
 zero
 fuckin
 fox
Cluster 252:  really
 like
 fucker
 forward
 fox
Cluster 253:  just like
 just
 like
 media
 popularity
Cluster 254:  ya
 know
 dumb
 fuck
 freedom
Cluster 255:  exactly
 zero
 fucker
 forward
 fox
Cluster 256:  continue
 comes
 fucker
 fox
 fox news
Cluster 257:  interesting
 think
 writing
 gullible
 enemies
Cluster 258:  joke
 fucking
 zero
 fuck just
 forum
Cluster 259:  obama
 xa0
 zero
 fucked
 forward
Cluster 260:  commenter
 trolling
 loser
 fucked
 forward
Cluster 261:  scumbag
 carter
 read
 forum
 forward
Cluster 262:  elected
 better
 zero
 fucker
 fox news
Cluster 263:  credit
 like
 zero
 fucked
 forward
Cluster 264:  ego
 makes
 zero
 fucker
 fox
Cluster 265:  important
 zero
 fucked
 forward
 fox
Cluster 266:  happening
 stay
 zero
 fucked
 forward
Cluster 267:  rock
 world
 zero
 forum
 forward
Cluster 268:  useful
 nthe
 fucker
 forward
 fox
Cluster 269:  double
 reta

A number of different metrics exist that allow us to measure how well the clusters fit the known distribution of underlying newsgroups. One such metric is the homogeneity which is a measure of how pure the clusters are with respect to the known labels (e.g. insult or neutral).

In [172]:
print "Homogeneity: %0.3f" % metrics.homogeneity_score(y_train, k_means.labels_)

Homogeneity: 0.196


Homogeneity scores vary between 0 and 1; a score of 1 indicates that the clusters match the original label distribution exactly.

Explore what happens if you make the number of clusters larger. What do you notice? Do the clusters of posts to the mailing lists begin to make more intuitive sense?

# Next Steps

If you have enjoyed this tutorial, the exercises in [Working With Data](http://scikit-learn.org/stable/tutorial/text_analytics/working_with_text_data.html) are a good next step.